<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LX-BLR-LT-009" failures="0" tests="7" name="LinkCxOWeb.TestCase.WebTestCases" time="21.052" errors="1" timestamp="2025-03-19T14:52:20 IST" skipped="4">
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="teardown" time="0.415">
    <error message="Cannot invoke &quot;org.openqa.selenium.WebDriver.quit()&quot; because &quot;LinkCxOWeb.TestCase.WebTestCases.driver&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "LinkCxOWeb.TestCase.WebTestCases.driver" is null
at LinkCxOWeb.TestCase.WebTestCases.teardown(WebTestCases.java:237)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- teardown -->
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="loginviaMobileNumber" time="16.470"/>
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="CreateJob" time="4.167"/>
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="CreateArticle">
    <skipped/>
  </testcase> <!-- CreateArticle -->
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="CreateQuery">
    <skipped/>
  </testcase> <!-- CreateQuery -->
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="CreatePost">
    <skipped/>
  </testcase> <!-- CreatePost -->
  <system-out/>
  <testcase classname="LinkCxOWeb.TestCase.WebTestCases" name="CreatePoll">
    <skipped/>
  </testcase> <!-- CreatePoll -->
  <system-out/>
</testsuite> <!-- LinkCxOWeb.TestCase.WebTestCases -->
